In [2]:
import numpy as np 

In [3]:
my_lois = [1,1,2]
my_lois

[1, 1, 2]

In [4]:
np.array(my_lois)

array([1, 1, 2])

In [5]:
arr = np.array(my_lois)

In [6]:
arr

array([1, 1, 2])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(5)
# this is always 0 to 1 

array([0.04409835, 0.68911902, 0.2130879 , 0.8983983 , 0.17849687])

In [22]:
np.random.randn(5)
# this is centred around 0

array([-0.10045562, -1.03515699,  1.3808092 , -0.46015422, -0.42131201])

In [23]:
np.random.randint(0,40,40)

array([32, 21, 21, 19, 16, 18,  1, 38, 23, 39, 32, 17, 32, 37, 15, 31, 25,
       38,  7, 25, 10,  0, 18, 30, 39, 33,  1,  1, 19,  5, 21, 24, 20, 11,
       31, 18, 25,  8, 30,  5])

In [24]:
arr = np.random.randint(0,100,50)
array = np.arange(0,41)


In [25]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

In [26]:
arr

array([80, 20, 28, 32, 19, 68, 76,  9, 32, 62, 43, 41, 38, 74, 41, 53, 51,
       82, 85, 33, 52, 74, 74,  8, 56, 57, 58, 85, 42, 86, 17, 16, 18, 75,
       41, 75,  4, 51,  9, 75, 29, 68, 57, 48, 78,  5, 39, 34, 77, 95])

In [27]:
arr.reshape(5,10)

array([[80, 20, 28, 32, 19, 68, 76,  9, 32, 62],
       [43, 41, 38, 74, 41, 53, 51, 82, 85, 33],
       [52, 74, 74,  8, 56, 57, 58, 85, 42, 86],
       [17, 16, 18, 75, 41, 75,  4, 51,  9, 75],
       [29, 68, 57, 48, 78,  5, 39, 34, 77, 95]])

In [28]:
arr.reshape(10,5)

array([[80, 20, 28, 32, 19],
       [68, 76,  9, 32, 62],
       [43, 41, 38, 74, 41],
       [53, 51, 82, 85, 33],
       [52, 74, 74,  8, 56],
       [57, 58, 85, 42, 86],
       [17, 16, 18, 75, 41],
       [75,  4, 51,  9, 75],
       [29, 68, 57, 48, 78],
       [ 5, 39, 34, 77, 95]])

In [29]:
arr.reshape(25,2)

array([[80, 20],
       [28, 32],
       [19, 68],
       [76,  9],
       [32, 62],
       [43, 41],
       [38, 74],
       [41, 53],
       [51, 82],
       [85, 33],
       [52, 74],
       [74,  8],
       [56, 57],
       [58, 85],
       [42, 86],
       [17, 16],
       [18, 75],
       [41, 75],
       [ 4, 51],
       [ 9, 75],
       [29, 68],
       [57, 48],
       [78,  5],
       [39, 34],
       [77, 95]])

In [30]:
arr.max()

95

In [31]:
arr.min()

4

In [32]:
arr.argmax()

49

In [33]:
arr.argmin()

36